### PR TITLE
Discourage response_requested = none, misc. updates

### PR DESCRIPTION
**Pull request by dlemire60**
- Separate language for TLS and HTTP suitability
- Proposed text discouraging `response_requested = none`
- Miscellaneous fine tuning.

### CODE REVIEW

**Comment by Vasileios-Mavroeidis** [comment]
@dlemire60 
https://github.com/oasis-tcs/openc2-impl-https/pull/106/commits/3d70fe405a0bdb007965261a23a1387a9a7f5d08
These are the 2 changes suggested regarding Section 1.8:
* The overhead of HTTP is acceptable (e.g., multiple OpenC2 Command / Response exchanges can be passed through a single HTTP connection).
* The overhead of establishing TLS sessions is acceptable

The first point still seems not good to me. Maybe something like the following is better.
"The possible overheard derived from multiple openc2 commands over an HTTP connection."

The first * implies that HTTP provides overhead by default. Its how i perceive it.

**Comment by dlemire60** [comment]
I think most people consider HTTP does have meaningful overhead, compared to lighter weight things like CoAP or maybe even MQTT. There's also the overhead of creating TCP and TLS sessions, which the second bullet only addresses part of. I guess the point the section was generally trying to make was to use HTTPS in "easy" network environments. WRT your suggestion, if anything sending multiple commands / responses through a single HTTP connection would be an efficiency, although I guess from HTTP v1.1 that's the usual way HTTP is operated.  Maybe replace both of those bullets with something like:
* The overhead of HTTP, TCP, and TLS are acceptable

and leave it at that?

Additionally, I'm now looking at the bullet above those:
* In-band negotiation of a connection initiated by either Producer or Consumer is possible without requiring an out-of-band signaling network.

and thinking it should be deleted.

**Comment by dlemire60** [comment]
I would appreciate feedback on this PR from @sparrell, @dmg2, @Vasileios-Mavroeidis

**Review by sparrell — APPROVED** [review]
works for me.

**Review by Vasileios-Mavroeidis — APPROVED** [review]
nicely articulated.

"The overhead of establishing TLS sessions is acceptable"  <- missing period

DLemire:  thanks, fixed.

**Pull request merged**
